### ISSUE TITLE
Start running page for documentation

### ISSUE THREAD

**Issue by cnwagwu** [govfresh/civicfolio#22]
All documentation can be found [here](https://www.notion.so/Documentation-a9e2bbdde9504befa65fcd86ec8c0ac3).

**Comment by cnwagwu** [comment]
This is a really good example of documentation that I will be using for the wiki: https://github.com/github/docs

**Comment by lukefretwell** [comment]
@cnwagwu love it!

**Comment by cnwagwu** [comment]
These two turned out to be better resources, we can talk through them today: https://github.com/atom/atom/blob/master/CONTRIBUTING.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question

https://mozillascience.github.io/working-open-workshop/contributing/#introduction

**Comment by cnwagwu** [comment]
- [x] Contributing Guide
- [ ] Add contact email to contributing guide
- [ ] Wiki: How to add/create a new page
- [ ] Wiki: How to add data to press links
- [ ] Wiki: How to add social media links
- [ ] Wiki: How to add data to work samples page
- [ ] Issue templates
- [ ] Pull request templates
