### ISSUE TITLE
Set up issue templates

### ISSUE THREAD

**Issue by lukefretwell** [govfresh/civicfolio#30]
@cnwagwu this would be something great for you to learn and think about from a project management and experience perspective. Great issues are the genesis to great collaboration.

Feel free to play around with it: https://github.com/govfresh/civicfolio/issues/templates/edit

## Reference

* https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
* https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates
* https://github.com/stevemao/github-issue-templates/

**Comment by cnwagwu** [comment]
Template code is here. I tried adding them and it doesn't appear to work for me: https://www.notion.so/Issue-and-Pull-Request-Templates-62cc4140bf0348c5b873fb1bd3496749

**Comment by lukefretwell** [comment]
Things to think about:

* issue types (help wanted, ops, etc.)
* labels (help wanted, wontfix)

**Comment by lukefretwell** [comment]
@cnwagwu I love this: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

Maybe we can make it as a separate ticket, but I love the idea of an interface like that.
